name: run-puppala-chkpt-taxi
 
jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest
    steps:
    - name: Install python
      uses: actions/setup-python@v3
 
    - name: Copy Repository contents
      uses: actions/checkout@main 
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run Checkpoint
      run: |
        python great_expectations/checkpoints/run_puppala_chkpt_taxi.py
